program cartera;

uses
  Forms,
  UnitdmColocacion in '..\..\units\UnitdmColocacion.pas' {dmColocacion: TDataModule},
  UnitCalculoCuotadePrueba in '..\..\units\UnitCalculoCuotadePrueba.pas' {frmCalculoCuotadePrueba},
  UnitCalculoTasas in '..\..\units\UnitCalculoTasas.pas' {frmCalculoTasas},
  UnitConsultaColocacion in '..\..\units\UnitConsultaColocacion.pas' {frmConsultaColocacion},
  UnitConsultaGarantias in '..\..\units\UnitConsultaGarantias.pas' {frmConsultaGarantias},
  UnitExtractoColocacion in '..\..\units\UnitExtractoColocacion.pas' {FrmExtractoColocacion},
  UnitInformeCreditosCancelados in '..\..\units\UnitInformeCreditosCancelados.pas' {frmInformeCreditosCancelados},
  UnitLiquidaciondePrueba in '..\..\units\UnitLiquidaciondePrueba.pas' {frmLiquidaciondePrueba},
  UnitMuestroLiquidacionColocacion in '..\..\units\UnitMuestroLiquidacionColocacion.pas' {frmMuestroLiquidacionColocacion},
  UnitTablaLiquidacion in '..\..\units\UnitTablaLiquidacion.pas' {frmTablaLiquidacion},
  UnitTablaPagoColocacion in '..\..\units\UnitTablaPagoColocacion.pas' {frmTablaPagoColocacion},
  UnitBuscarControlCobro in '..\..\units\UnitBuscarControlCobro.pas' {frmBusquedaControlCobro},
  UnitBuscarPersona in '..\..\units\UnitBuscarPersona.pas' {frmBuscarPersona},
  UnitBuscarTexto in '..\..\units\UnitBuscarTexto.pas' {frmBuscarTexto},
  UnitControlCobroCartera in '..\..\units\UnitControlCobroCartera.pas' {FrmControlCobroCartera},
  UnitDireccionesAsociados in '..\..\units\UnitDireccionesAsociados.pas' {frmDireccionesAsociado},
  UnitPantallaProgreso in '..\..\units\UnitPantallaProgreso.pas' {frmProgreso},
  UnitConsultaLiquidacion in '..\..\units\UnitConsultaLiquidacion.pas' {frmConsultaLiquidacion},
  UnitInformeColocacionesporestado in '..\..\units\UnitInformeColocacionesporestado.pas' {frminformecolocacionesporestado},
  Unitcomparartabla in '..\..\units\Unitcomparartabla.pas' {frmcomparartabla},
  UnitBarridoCartera in '..\..\units\UnitBarridoCartera.pas' {frmBarridoCartera},
  UnitdmPersona in '..\..\units\UnitdmPersona.pas' {dmPersona: TDataModule},
  UnitRecuperarBarridoCartera in '..\..\units\UnitRecuperarBarridoCartera.pas' {frmRecuperarBarridoCartera},
  Consts in '..\..\units\Consts.pas',
  UnitCargarCostasJudiciales in '..\..\units\UnitCargarCostasJudiciales.pas' {frmCargarCostasJudiciales},
  UnitCambiarContrasena in '..\..\units\UnitCambiarContrasena.pas' {frmCambiarContrasena},
  unitLogin in '..\..\units\unitLogin.pas' {frmLogin},
  UnitdmGeneral in '..\..\units\UnitdmGeneral.pas' {dmGeneral: TDataModule},
  UnitCreaciondePersona in '..\..\units\UnitCreaciondePersona.pas' {frmCreacionPersona},
  unitMain in 'Unit\unitMain.pas' {frmMain},
  UnitConsultaProductos in '..\..\units\UnitConsultaProductos.pas' {frmConsultaProductos},
  UnitObservacionesCambioEstado in '..\..\units\UnitObservacionesCambioEstado.pas' {frmObservacionesCambioEstado},
  UnitInformeCobroConstante in '..\..\units\UnitInformeCobroConstante.pas' {frmInformeCobroConstante},
  UnitRecuperarTablaLiq in '..\..\units\UnitRecuperarTablaLiq.pas' {frmRecuperarTablaLiq},
  UnitMarcarProrroga in '..\..\units\UnitMarcarProrroga.pas' {frmMarcarProrroga},
  UnitEnvioJudicialCastigada in '..\..\units\UnitEnvioJudicialCastigada.pas' {frmEnvioJudicialCastigada},
  UnitLiquidacionExtraordinaria1 in '..\..\units\UnitLiquidacionExtraordinaria1.pas' {frmLiquidacionExtraordinaria1},
  UnitBuscarColocacion in '..\..\units\UnitBuscarColocacion.pas' {frmBusquedadeColocacion},
  UnitReLogin in '..\..\units\UnitReLogin.pas' {frmReLogin},
  UnitBuscarEscritura in '..\..\units\UnitBuscarEscritura.pas' {frmBusquedadeEscritura},
  digitacuenta in '..\..\units\digitacuenta.pas' {digita},
  Unit_Comprobante in '..\..\units\Unit_Comprobante.pas' {frmComprobante},
  Unit_Mantenimientopuc in '..\..\units\Unit_Mantenimientopuc.pas' {frmMantenimientopuc},
  Unit_Dmpuc in '..\..\units\Unit_Dmpuc.pas' {Dmpuc: TDataModule},
  Unit_BuscarCodigo in '..\..\units\Unit_BuscarCodigo.pas' {frmBuscarCodigo},
  Unit_BuscarClave in '..\..\units\Unit_BuscarClave.pas' {frmBuscarClave},
  Unit_buscarcomprobante in '..\..\units\Unit_buscarcomprobante.pas' {frmbuscarcomprobante},
  UnitLiquidacionCastigada in '..\..\units\UnitLiquidacionCastigada.pas' {frmLiquidacionCastigada},
  UnitInformeColocacionFiltrado in '..\..\units\Copia 120404\UnitInformeColocacionFiltrado.pas' {frmInformeColocacionesFiltrado},
  UnitReversionAbonoCartera in '..\..\units\UnitReversionAbonoCartera.pas' {frmReversionAbonoCartera},
  UnitCausacionColocaciones in '..\..\units\UnitCausacionColocaciones.pas' {frmCausacionColocaciones},
  UnitVistaPreliminar in '..\..\units\UnitVistaPreliminar.pas' {frmVistaPreliminar},
  UnitInformeDiarioCartera in '..\..\units\UnitInformeDiarioCartera.pas' {frmInformeDiarioCartera},
  UnitEstadoCaptacionporCartera in '..\..\units\UnitEstadoCaptacionporCartera.pas' {frmEstadoCaptacionporCartera},
  UnitInformeAseguradoraCartera in '..\..\units\UnitInformeAseguradoraCartera.pas' {frmInformeAseguradoraCartera},
  UnitControldeObservaciones in '..\..\units\UnitControldeObservaciones.pas' {frmControldeObservaciones},
  UnitRegistrarObservacion in '..\..\units\UnitRegistrarObservacion.pas' {frmRegistrarObservacion},
  UnitRecuperarLiquidacionColocacion in '..\..\units\UnitRecuperarLiquidacionColocacion.pas' {frmRecuperarLiquidacionColocacion},
  UnitMantenimientoAbogados in '..\..\units\UnitMantenimientoAbogados.pas' {frmMantenimientoAbogados},
  UnitRCarteraAbogados in '..\..\units\UnitRCarteraAbogados.pas' {frmRCarteraAbogados},
  UnitImpresion in '..\..\units\UnitImpresion.pas' {FrmImpresion},
  UnitConsultaExtractoCaptacion in '..\..\units\UnitConsultaExtractoCaptacion.pas' {frmConsultaExtractoCaptacion},
  Unit_DmComprobante in '..\..\units\Unit_DmComprobante.pas' {DmComprobante: TDataModule},
  Videocap in '..\..\units\Videocap.pas',
  UnitTomaHuella in '..\..\units\UnitTomaHuella.pas' {frmRegister},
  UnitTomarFoto in '..\..\units\UnitTomarFoto.pas' {frmTomarFoto},
  VFW in '..\..\units\VfW.pas',
  UnitVerificarHuella in '..\..\units\UnitVerificarHuella.pas' {frmVerify},
  UnitConsultaSol in '..\..\units\UnitConsultaSol.pas' {FrmConsultaSol},
  UnitLiquidacionGral in '..\..\units\UnitLiquidacionGral.pas' {frmLiquidacionGral},
  UnitDmSolicitud in '..\..\units\UnitDmSolicitud.pas' {DmSolicitud: TDataModule},
  UnitDescObservacion in '..\..\units\UnitDescObservacion.pas' {FrmDescObsrevacion},
  UnitControlCarta in '..\..\units\UnitControlCarta.pas' {FrmControlCarta},
  UnitTipoImpresion in '..\..\units\UnitTipoImpresion.pas' {frmTipoImpresion},
  UnitDiasEntreFechas in '..\..\units\UnitDiasEntreFechas.pas' {frmDiasEntreFechas},
  UnitFechaAEvaluar in 'Unit\UnitFechaAEvaluar.pas' {frmFechas},
  UnitRelacionChequesEnCanje in '..\..\units\UnitRelacionChequesEnCanje.pas' {frmRelacionChequesEnCanje},
  UnitLiquidacionJudicialDes in '..\..\units\UnitLiquidacionJudicialDes.pas' {frmLiquidacionJudicialDes},
  UnitColocaciones in '..\..\units\UnitColocaciones.pas' {FrmColocacion},
  DataSetToExcel in '..\..\units\DataSetToExcel.pas',
  UnitReporteReversionCartera in '..\..\units\UnitReporteReversionCartera.pas' {frmReporteReversionCartera},
  UnitEndosoPagare in '..\..\units\UnitEndosoPagare.pas' {FrmEndosoPagare},
  UnitReporteEndoso in '..\..\units\UnitReporteEndoso.pas' {FrmReporteEndoso},
  UnitDescargaPagare in '..\..\units\UnitDescargaPagare.pas' {FrmDescargaPagare},
  UnitReporteCambioEstadoColocacion in '..\..\units\UnitReporteCambioEstadoColocacion.pas' {frmReporteCambioEstadoColocacion},
  UnitInformeCarteraPrivilegiados in '..\..\units\UnitInformeCarteraPrivilegiados.pas' {frmInformeCarteraPrivilegiados},
  UnitExtractoCredito in '..\..\units\UnitExtractoCredito.pas' {frmExtractoCredito},
  UnitResumenColocaciones in '..\..\units\UnitResumenColocaciones.pas' {frmResumenColocaciones},
  UnitMidificaLinea in '..\..\units\UnitMidificaLinea.pas' {FrmModificaLinea},
  UnitConsolidarPlanoBancoldex in '..\..\units\UnitConsolidarPlanoBancoldex.pas' {frmConsolidarPlanoBancoldex},
  UnitRecuperacionesCartera in '..\..\units\UnitRecuperacionesCartera.pas' {frmRecuperacionesCartera},
  UnitCausacionCarteraDiaria in '..\..\units\UnitCausacionCarteraDiaria.pas' {frmCausacionCarteraDiaria},
  UnitAgregarObservacion in '..\..\units\UnitAgregarObservacion.pas' {frmAgregarObservacionCobro},
  UnitAgregarActuacion in 'Cambios Abogados 20061226\UnitAgregarActuacion.pas' {frmAgregarActuacion},
  UnitInformeAsociadosporMunicipio in '..\..\units\UnitInformeAsociadosporMunicipio.pas' {frmInformeAsociadosporMunicipio},
  UnitInformeAsociadosMercado in 'UnitInformeAsociadosMercado.pas' {frmInformeAsociadosporMercado},
  UnitAsignacionAbogado in '..\..\units\UnitAsignacionAbogado.pas' {frmAsignacionAbogado},
  UnitCambios in '..\..\units\UnitCambios.pas' {FrmCambios},
  UnitAgregarObservacionSol in '..\..\units\UnitAgregarObservacionSol.pas' {frmAgregarObservacionSol},
  UnitLiquidacionCarteraJudicial in '..\..\units\UnitLiquidacionCarteraJudicial.pas' {frmLiquidacionCarteraJudicial},
  UnitBuscarCiiu in '..\..\units\UnitBuscarCiiu.pas' {frmBuscarCIIU},
  UnitCreacionPersonaIndependiente in '..\..\units\UnitCreacionPersonaIndependiente.pas' {frmCreacionPersonaIndependiente},
  UnitGlobalesCol in '..\..\Globales\UnitGlobalesCol.pas',
  UnitGlobales in '..\..\Globales\UnitGlobales.pas',
  UnitInformeDiarioDesembolsos in '..\..\Units\UnitInformeDiarioDesembolsos.pas' {frmInformeDiarioDesembolsos},
  UnitGeneraCartas in '..\..\Units\UnitGeneraCartas.pas' {FrmGeneraCarta},
  UnitRecaudoCuotaProyectada in '..\..\Units\UnitRecaudoCuotaProyectada.pas' {frmRecaudoCuotaProyectada};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Cartera';
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
