program Captaciones98;

uses
  Forms,
  unitMain in 'Units\unitMain.pas' {frmMain},
  UnitdmGeneral in '..\..\units\UnitdmGeneral.pas' {dmGeneral: TDataModule},
  UnitVistaPreliminar in '..\..\units\UnitVistaPreliminar.pas' {frmVistaPreliminar},
  UnitBuscarTexto in '..\..\units\UnitBuscarTexto.pas' {frmBuscarTexto},
  UnitCaptaciones in '..\..\units\UnitCaptaciones.pas',
  UnitConsultaExtractoCaptacion in '..\..\units\UnitConsultaExtractoCaptacion.pas' {frmConsultaExtractoCaptacion},
  UnitCreacionCaptacion in '..\..\units\UnitCreacionCaptacion.pas' {frmCreacionCaptacion},
  UnitCreaciondePersona in '..\..\units\UnitCreaciondePersona.pas' {frmCreacionPersona},
  UnitdmCaptacion in '..\..\units\UnitdmCaptacion.pas' {dmCaptacion: TDataModule},
  UnitdmColocacion in '..\..\units\UnitdmColocacion.pas' {dmColocacion: TDataModule},
  UnitdmLiquidacionCaptacion in '..\..\units\UnitdmLiquidacionCaptacion.pas' {dmLiquidacionCaptacion: TDataModule},
  UnitdmPersona in '..\..\units\UnitdmPersona.pas' {dmPersona: TDataModule},
  UnitEfectivoNota in '..\..\units\UnitEfectivoNota.pas' {frmEfectivoNota},
  UnitImpresionCaptacion in '..\..\units\UnitImpresionCaptacion.pas' {frmImpresionCaptacion},
  UnitInformeGeneraldeCaptaciones in '..\..\units\UnitInformeGeneraldeCaptaciones.pas' {frmInformeGeneraldeCaptaciones},
  UnitLiquidacionInteresesCaptacion in '..\..\units\UnitLiquidacionInteresesCaptacion.pas' {frmLiquidacionInteresesCaptacion},
  unitLogin in '..\..\units\unitLogin.pas' {frmLogin},
  UnitMantenimientoCaptacion in '..\..\units\UnitMantenimientoCaptacion.pas' {frmMantenimientoCaptacion},
  UnitPantallaProgreso in '..\..\units\UnitPantallaProgreso.pas' {frmProgreso},
  UnitProrrogaCaptaciones in '..\..\units\UnitProrrogaCaptaciones.pas' {frmProrrogaCaptacion},
  UnitRangosdeLibreta in '..\..\units\UnitRangosdeLibreta.pas' {frmRangosdeLibreta},
  UnitRecuperarTablaLiquidacionCaptacion in '..\..\units\UnitRecuperarTablaLiquidacionCaptacion.pas' {frmRecuperarTablaLiquidacionCaptacion},
  UnitSaldarCaptacion in '..\..\units\UnitSaldarCaptacion.pas' {frmSaldarCaptacion},
  UnitTomarFoto in '..\..\units\UnitTomarFoto.pas' {frmTomarFoto},
  UnitValidarCaptacion in '..\..\units\UnitValidarCaptacion.pas' {frmValidarCaptacion},
  UnitBuscarPersona in '..\..\units\UnitBuscarPersona.pas' {frmBuscarPersona},
  Consts in '..\..\units\Consts.pas',
  UnitConsultaCaptacion in '..\..\units\UnitConsultaCaptacion.pas' {frmConsultaCaptacion},
  UnitImagenAmpliada in '..\..\units\UnitImagenAmpliada.pas' {frmImagenAmpliada},
  Unit_DmComprobante in '..\..\units\Unit_DmComprobante.pas' {DmComprobante: TDataModule},
  Unit_buscarcomprobante in '..\..\units\Unit_buscarcomprobante.pas' {frmbuscarcomprobante},
  Unit_Comprobante in '..\..\units\Unit_Comprobante.pas' {frmComprobante},
  Unit_Dmpuc in '..\..\units\Unit_Dmpuc.pas' {Dmpuc: TDataModule},
  Unit_Mantenimientopuc in '..\..\units\Unit_Mantenimientopuc.pas' {frmMantenimientopuc},
  Unit_BuscarClave in '..\..\units\Unit_BuscarClave.pas' {frmBuscarClave},
  Unit_BuscarCodigo in '..\..\units\Unit_BuscarCodigo.pas' {frmBuscarCodigo},
  digitacuenta in '..\..\units\digitacuenta.pas' {digita},
  UnitGlobales in '..\..\Globales\UnitGlobales.pas',
  UnitGlobalesCol in '..\..\Globales\UnitGlobalesCol.pas',
  UnitEstadoCaptacion in '..\..\units\UnitEstadoCaptacion.pas' {frmEstadoCaptacion},
  UnitTasaPromedioCertificados in '..\..\units\UnitTasaPromedioCertificados.pas' {frmTasaPromedioCertificados},
  UnitListadoGeneralCaptaciones in '..\..\units\UnitListadoGeneralCaptaciones.pas' {frmListadoGeneralCaptaciones},
  UnitSumatorias in '..\..\units\UnitSumatorias.pas' {frmSumatorias},
  UnitCambiarContrasena in '..\..\units\UnitCambiarContrasena.pas' {frmCambiarContrasena},
  UnitControlCobroCartera in '..\..\units\UnitControlCobroCartera.pas' {frmControlCobroCartera},
  UnitCalculoTasas in '..\..\units\UnitCalculoTasas.pas' {frmCalculoTasas},
  UnitAgregarObservacion in '..\..\units\UnitAgregarObservacion.pas' {frmAgregarObservacionCobro},
  UnitConsultaLiquidacion in '..\..\units\UnitConsultaLiquidacion.pas' {frmConsultaLiquidacion},
  UnitBuscarColocacion in '..\..\units\UnitBuscarColocacion.pas' {frmBusquedadeColocacion},
  UnitConsultaGarantias in '..\..\units\UnitConsultaGarantias.pas' {frmConsultaGarantias},
  UnitDireccionesAsociados in '..\..\units\UnitDireccionesAsociados.pas' {frmDireccionesAsociado},
  UnitObservacionesCambioEstado in '..\..\units\UnitObservacionesCambioEstado.pas' {frmObservacionesCambioEstado},
  UnitVerificarHuella in '..\..\units\UnitVerificarHuella.pas' {frmVerify},
  UnitTomaHuella in '..\..\units\UnitTomaHuella.pas' {frmRegister},
  UnitActayEducacion in '..\..\units\UnitActayEducacion.pas' {frmActayEducacion},
  UnitInformeTasaPromedio in '..\..\units\UnitInformeTasaPromedio.pas' {frmInformeTasaPromedio},
  UnitExtractoColocacion in '..\..\units\UnitExtractoColocacion.pas' {FrmExtractoColocacion},
  UnitBuscarControlCobro in '..\..\units\UnitBuscarControlCobro.pas' {frmBusquedaControlCobro},
  UnitReLogin in '..\..\units\UnitReLogin.pas' {frmReLogin},
  UnitProyeccionPagoCDAT in '..\..\units\UnitProyeccionPagoCDAT.pas' {frmProyeccionPagoCDAT},
  UnitInformePorRangosCaptacion in '..\..\units\UnitInformePorRangosCaptacion.pas' {frmInformeCaptacionesporRango},
  UnitAsignarTarjetaDebito in '..\..\units\UnitAsignarTarjetaDebito.pas' {frmAsignarTarjetaDebito},
  unitCausacionCdat in '..\..\units\otraunit\unitCausacionCdat.pas' {frmcausacioncdat},
  UnitInactivacionCaptaciones in '..\..\units\UnitInactivacionCaptaciones.pas' {frmInactivacionCaptaciones},
  UnitInformeCuentasporEstado in '..\..\units\UnitInformeCuentasporEstado.pas' {frmInformeCuentasporEstado},
  UnitConsignacionNacional in '..\..\units\UnitConsignacionNacional.pas' {frmConsignacionNacional},
  UnitConsultaProductos in '..\..\units\UnitConsultaProductos.pas' {frmConsultaProductos},
  UnitControldeObservaciones in '..\..\units\UnitControldeObservaciones.pas' {frmControldeObservaciones},
  UnitRegistrarObservacion in '..\..\units\UnitRegistrarObservacion.pas' {frmRegistrarObservacion},
  UnitListadoCaptacionesConsolidado in '..\..\units\UnitListadoCaptacionesConsolidado.pas' {frmListadoCaptacionesConsolidado};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Captaciones';
  Application.CreateForm(TdmGeneral, dmGeneral);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
