program Tesoreria;

uses
  Forms,
  unitMain in 'Units\unitMain.pas' {frmMain},
  UnitRangosdeLibreta in '..\..\units\UnitRangosdeLibreta.pas' {frmRangosdeLibreta},
  UnitVistaPreliminar in '..\..\units\UnitVistaPreliminar.pas' {frmVistaPreliminar},
  Consts in '..\..\units\Consts.pas',
  UnitdmCaptacion in '..\..\units\UnitdmCaptacion.pas' {dmCaptacion: TDataModule},
  UnitdmColocacion in '..\..\units\UnitdmColocacion.pas' {dmColocacion: TDataModule},
  UnitdmGeneral in '..\..\units\UnitdmGeneral.pas' {dmGeneral: TDataModule},
  UnitdmPersona in '..\..\units\UnitdmPersona.pas' {dmPersona: TDataModule},
  UnitGlobales in '..\..\Globales\UnitGlobales.pas',
  UnitImagenAmpliada in '..\..\units\UnitImagenAmpliada.pas' {frmImagenAmpliada},
  UnitImagenesPersona in '..\..\units\UnitImagenesPersona.pas' {frmImagenesPersona},
  unitLogin in '..\..\units\unitLogin.pas' {frmLogin},
  UnitPantallaProgreso in '..\..\units\UnitPantallaProgreso.pas' {frmProgreso},
  UnitConsultaProductos in '..\..\units\UnitConsultaProductos.pas' {frmConsultaProductos},
  UnitBuscarCaptacion in '..\..\units\UnitBuscarCaptacion.pas' {frmBuscarCaptacion},
  UnitBuscarColocacion in '..\..\units\UnitBuscarColocacion.pas' {frmBusquedadeColocacion},
  UnitBuscarPersona in '..\..\units\UnitBuscarPersona.pas' {frmBuscarPersona},
  UnitBuscarTexto in '..\..\units\UnitBuscarTexto.pas' {frmBuscarTexto},
  UnitConsultaExtractoCaptacion in '..\..\units\UnitConsultaExtractoCaptacion.pas' {frmConsultaExtractoCaptacion},
  UnitTomarFoto in '..\..\units\UnitTomarFoto.pas' {frmTomarFoto},
  Unit_DmComprobante in '..\..\units\Unit_DmComprobante.pas' {DmComprobante: TDataModule},
  Unit_Comprobante in '..\..\units\Unit_Comprobante.pas' {frmComprobante},
  Unit_Dmpuc in '..\..\units\Unit_Dmpuc.pas' {Dmpuc: TDataModule},
  Unit_buscarcomprobante in '..\..\units\Unit_buscarcomprobante.pas' {frmbuscarcomprobante},
  digitacuenta in '..\..\units\digitacuenta.pas' {digita},
  UnitChequesenTesoreria in '..\..\units\UnitChequesenTesoreria.pas' {frmChequesenTesoreria},
  UnitLiberacionCanje in '..\..\units\UnitLiberacionCanje.pas' {frmLiberacionCanje},
  Unit_Mantenimientopuc in '..\..\units\Unit_Mantenimientopuc.pas' {frmMantenimientopuc},
  Unit_BuscarCodigo in '..\..\units\Unit_BuscarCodigo.pas' {frmBuscarCodigo},
  Unit_BuscarClave in '..\..\units\Unit_BuscarClave.pas' {frmBuscarClave},
  UnitValidarColocacion in '..\..\units\UnitValidarColocacion.pas' {frmValidarColocacion},
  UnitRelacionCheques in '..\..\units\UnitRelacionCheques.pas' {frmRelacionCheques},
  UnitArqueoDevolucion in '..\..\units\UnitArqueoDevolucion.pas' {frmArqueoDevolucion},
  UnitChequesenCaja in '..\..\units\UnitChequesenCaja.pas' {frmChequesenCaja},
  UnitCierreDiarioCaja in '..\..\units\UnitCierreDiarioCaja.pas' {frmCierreDiarioCaja},
  UnitComprobanteDiarioCaja in '..\..\units\UnitComprobanteDiarioCaja.pas' {frmComprobanteDiario},
  UnitActualizarArqueo in '..\..\units\UnitActualizarArqueo.pas' {frmActualizarArqueo},
  UnitCambiarContrasena in '..\..\units\UnitCambiarContrasena.pas' {frmCambiarContrasena},
  UnitControlCobroCartera in '..\..\units\UnitControlCobroCartera.pas',
  UnitAgregarObservacion in '..\..\units\UnitAgregarObservacion.pas' {frmAgregarObservacionCobro},
  UnitConsultaLiquidacion in '..\..\units\UnitConsultaLiquidacion.pas' {frmConsultaLiquidacion},
  UnitConsultaGarantias in '..\..\units\UnitConsultaGarantias.pas' {frmConsultaGarantias},
  UnitDireccionesAsociados in '..\..\units\UnitDireccionesAsociados.pas' {frmDireccionesAsociado},
  UnitCreaciondePersona in '..\..\units\UnitCreaciondePersona.pas' {frmCreacionPersona},
  UnitInformeAuxiliar in '..\..\units\UnitInformeAuxiliar.pas' {frmInformeAuxiliares},
  UnitObservacionesCambioEstado in '..\..\units\UnitObservacionesCambioEstado.pas' {frmObservacionesCambioEstado},
  UnitExtractoColocacion in '..\..\units\UnitExtractoColocacion.pas' {FrmExtractoColocacion},
  UnitBuscarControlCobro in '..\..\units\UnitBuscarControlCobro.pas' {frmBusquedaControlCobro},
  Unittesoreria in '..\..\units\Unittesoreria.pas' {Frmtesoreria},
  UnitChequesSinLiberar in '..\..\units\UnitChequesSinLiberar.pas' {frmChequesSinLiberar},
  UnitReLogin in '..\..\units\UnitReLogin.pas' {frmReLogin},
  UnitControldeObservaciones in '..\..\units\UnitControldeObservaciones.pas' {frmControldeObservaciones},
  UnitRegistrarObservacion in '..\..\units\UnitRegistrarObservacion.pas' {frmRegistrarObservacion},
  UnitImpresion in '..\..\units\UnitImpresion.pas' {FrmImpresion},
  VFW in '..\..\units\VfW.pas',
  Videocap in '..\..\units\Videocap.pas',
  UnitVerificarHuella in '..\..\units\UnitVerificarHuella.pas' {frmVerify},
  UnitTomaHuella in '..\..\units\UnitTomaHuella.pas' {frmRegister},
  UnitConsultaSol in '..\..\units\UnitConsultaSol.pas' {FrmConsultaSol},
  UnitDescObservacion in '..\..\units\UnitDescObservacion.pas' {FrmDescObsrevacion},
  UnitLiquidacionGral in '..\..\units\UnitLiquidacionGral.pas' {frmLiquidacionGral},
  UnitDmSolicitud in '..\..\units\UnitDmSolicitud.pas' {DmSolicitud: TDataModule},
  UnitTipoImpresion in '..\..\units\UnitTipoImpresion.pas' {frmTipoImpresion},
  UnitComprobanteSucursal in '..\..\units\UnitComprobanteSucursal.pas' {FrmComprobanteSucursal},
  UnitRelacionChequesEnCanje in '..\..\units\UnitRelacionChequesEnCanje.pas' {frmRelacionChequesEnCanje},
  UnitInformeCajaRemota in '..\..\units\UnitInformeCajaRemota.pas' {FrmInformeCajaRemota},
  UnitVisacionRetiros in '..\..\units\UnitVisacionRetiros.pas' {frmVisacionRetiros},
  UnitExtractoCredito in '..\..\units\UnitExtractoCredito.pas' {frmExtractoCredito},
  UnitSaldosCaja in '..\..\units\UnitSaldosCaja.pas' {FrmSaldosCaja},
  UnitCertificadoRetefuente in '..\..\units\UnitCertificadoRetefuente.pas' {frmCertificadoRetefuente},
  UnitCertificadoReteIva in '..\..\units\UnitCertificadoReteIva.pas' {frmCertificadoReteIva},
  UnitInformeTesoreriaExcentasGMF in 'Units\UnitInformeTesoreriaExcentasGMF.pas' {frmInformeTesoreriaExcentasGMF},
  UnitCambios in '..\..\units\UnitCambios.pas' {FrmCambios},
  UnitAgregarObservacionSol in '..\..\units\UnitAgregarObservacionSol.pas' {frmAgregarObservacionSol},
  UnitFechaSucursal in '..\..\units\UnitFechaSucursal.pas' {FrmFechaSucursal},
  UnitExtractoAgencia in '..\..\units\UnitExtractoAgencia.pas' {FrmExtractoAgencia},
  UnitBuscarCiiu in '..\..\units\UnitBuscarCiiu.pas' {frmBuscarCIIU},
  UnitPlanillaGMF in '..\..\units\UnitPlanillaGMF.pas' {frmPlanillaGMF},
  DataSetToExcel in '..\..\units\DataSetToExcel.pas',
  DpSdkEngLib_TLB in '..\..\..\Archivos de programa\Borland\Delphi6\Imports\DpSdkEngLib_TLB.pas',
  UnitDevolucionCheques in '..\..\units\UnitDevolucionCheques.pas' {frmDevolucionCheques},
  UnitConsultarListado in '..\..\Units\UnitConsultarListado.pas' {frmVerListados},
  UnitGlobalesCol in '..\..\Globales\UnitGlobalesCol.pas',
  UnitCreacionPersonaIndependiente in '..\..\Units\UnitCreacionPersonaIndependiente.pas' {frmCreacionPersonaIndependiente},
  UnitGeneraCartas in '..\..\Units\UnitGeneraCartas.pas' {FrmGeneraCarta};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Módulo Tesorería';
  Application.CreateForm(TdmGeneral, dmGeneral);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
